### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Nodeswitch** [Juvar1/APRSterminal#1]
Hey - I've just tried running this on my system, but I'm getting the below traceback. 

```
➜ sudo python3 APRSterminal.py 
Traceback (most recent call last):
  File "APRSterminal.py", line 25, in <module>
    from PyQt4 import QtGui, QtCore, QtWebKit
ImportError: cannot import name QtWebKit

➜ python3 --version
Python 3.6.5

```
Looks like PyQt4.QtWebKit isn't maintained on PyQt4 [anymore](https://askubuntu.com/questions/840318/importerror-no-module-named-pyqt4-qtwebkit). [Same with Qt5, apparently](https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5/37877273?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

**Comment by Juvar1** [comment]
787ea5d Now there is a new file called APRSterminalP3.py. It works with Python version 3.6 and replaces the old file APRSterminal.py that is intended to Python version 2.7. New file does not use QtWebKit anymore.
